---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: true

- name: Remove default nginx config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload nginx

- name: Add custom nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/sites-available/my_site
  notify: Reload nginx

- name: Enable custom config
  file:
    src: /etc/nginx/sites-available/my_site
    dest: /etc/nginx/sites-enabled/my_site
    state: link

- name: Test nginx config
  command: nginx -t

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
  when: nginx_config_changed is defined and nginx_config_changed
